#!/usr/bin/env bash
set -e

BUILD_FLAG=""
DOXYGEN_FLAG=""

for arg in "$@"; do
    case $arg in
        -b|--build)
            BUILD_FLAG="--build"
            ;;
        -d|--docs)
            DOXYGEN_FLAG="&& cd /root/pico_lib/include && doxygen /root/app/docs/Doxyfile"
            ;;
        -h|--help)
            echo "Usage: $0 [-b|--build] [-d|--docs]"
            echo "  -b, --build   Build the project"
            echo "  -d, --docs    Generate Doxygen docs"
            exit 0
            ;;
        *)
            echo "Unknown option: $arg"
            echo "Usage: $0 [-b|--build] [-d|--docs]"
            exit 1
            ;;
    esac
done

docker compose up pico_sdk $BUILD_FLAG --force-recreate --remove-orphans -d

docker compose exec -it pico_sdk sh -c "\
  cp /root/pico-sdk/external/pico_sdk_import.cmake /root/app/ && \
  cp /root/pico-sdk/external/pico_sdk_import.cmake /root/pico_lib/ && \
  cd /root/app && \
  cmake -S . -B build && \
  cmake --build build -j\$(nproc) \
  $DOXYGEN_FLAG
"

docker compose down
